---
title: "Financial Data Analystics Project Report"
author: "Marklina Yakopa"
date: "November 19th  2024"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#"Answers-to-Questions-1-to-7"
```

## 1. Exploratory data analysis I: 15 points
 

```{r}
### Problem 1
da=read.table("d-sbux3dx-0715.txt",header=T)
head(da)
rtn=da[,3:6]
attach(rtn)
require(fBasics)
# (a)
basicStats(SBUX)
basicStats(vwretd)
basicStats(ewretd)
basicStats(sprtrn)
# (b)
densitySBUX=density(rtn$SBUX)
plot(densitySBUX)
# This is the same density plot but with labels
plot(densitySBUX,xlab='return',ylab='SBUX',main='Density')
normalTest(SBUX)
# (c)
lrtn=log(rtn+1) ### log returns
basicStats(lrtn$SBUX)
basicStats(lrtn$vwretd)
basicStats(lrtn$ewretd)
basicStats(lrtn$sprtrn)
# (d)
t.test(lrtn$SBUX)
t.test(lrtn$sprtrn)
# (e)
densitylogSBUX=density(lrtn$SBUX)
densitylogvwretd=density(lrtn$vwretd)
par(mfcol=c(1,2)) ## Put two plots in a frame (left and right)
plot(densitylogSBUX,xlab='log-return',ylab='SBUX',main='Density')
plot(densitylogSBUX,xlab='log-return',ylab='vw index',main='Density')
par(mfcol=c(1,1))

```

## 2. Factor models: 30 points

```{r}
# Problem 2
FFfactors <- read.csv("C:/Users/Administrator/Desktop/Assignment for Marklina/FamaFrenchFactors (1).csv",header=T) # Load csv data with names.
head(FFfactors) # See the first 6 rows
attach(FFfactors) #Now you can refer directly to the names of the variables.
#Note that you might receive a warning: "The following objects are masked from FFfactors ..."
# This just means that you are overwriting variables with these names that you have used before.
# For our purposes you can simply ignore this message.
names(FFfactors)
rf <- read.csv("C:/Users/Administrator/Desktop/Assignment for Marklina/RiskFreeRate.csv",header=T) # Load csv data with names.
head(rf) # See the first 6 rows
sv <- read.csv("C:/Users/Administrator/Desktop/Assignment for Marklina/SizeValuePortfolios.csv",header=T) # Load csv data with names.
head(sv) # See the first 6 rows
names(sv)
Industry=read.csv("C:/Users/Administrator/Desktop/Assignment for Marklina/IndustryPortfolios.csv",header=T) # Load csv data with names.
head(Industry) # See the first 6 rows
names(Industry)
# (a)
Industry=Industry[,2:31]
attach(Industry) #Now you can refer directly to the names of the variables.
#Note that you might receive a warning: "The following objects are masked from..."
# This just means that you are overwriting variables with these names that you have used before.
# For our purposes you can simply ignore this message.
industrypca=prcomp(Industry)
summary(industrypca)
plot(industrypca)
# (b)
fitSteel=lm(Steel~industrypca$x[,1:3])
summary(fitSteel)
plot(Steel,fitSteel$fitted.values)
abline(c(0,1))
fitSteel2=lm(Steel~Mkt)
summary(fitSteel2)
plot(Steel,fitSteel2$fitted.values)
abline(c(0,1))
fitFood=lm(Food~industrypca$x[,1:3])
summary(fitFood)
plot(Food,fitFood$fitted.values)
abline(c(0,1))
fitFood2=lm(Steel~Mkt)
summary(fitFood2)
plot(Food,fitFood2$fitted.values)
abline(c(0,1))

#(c)
svrf=sv[,2:26]-rf$RF

# (d)  
fit1=lm(svrf[[2]]~Mkt)
summary(fit1)
fit3=lm(svrf[[15]]~Mkt)
summary(fit3)

# (e)
fit1=lm(svrf[[2]]~Mkt)
summary(fit1)
fit3=lm(svrf[[15]]~Mkt)
summary(fit3)

# (f)
fit2=lm(svrf[[2]]~Mkt+SMB+HML)
summary(fit2)
fit4=lm(svrf[[15]]~Mkt+SMB+HML)
summary(fit4)

# (g)
library(lmtest)
library(sandwich)
coeftest(fit1, vcov = vcov(fit1))
coeftest(fit1, vcov = NeweyWest(fit1))
coeftest(fit2, vcov = vcov(fit2))
coeftest(fit2, vcov = NeweyWest(fit2))
coeftest(fit3, vcov = vcov(fit3))
coeftest(fit3, vcov = NeweyWest(fit3))
coeftest(fit4, vcov = vcov(fit4))
coeftest(fit4, vcov = NeweyWest(fit4))

# (h)
pcasv=prcomp(svrf)
plot(pcasv)
# (i)
fit5=lm(Mkt~pcasv$x[,(1:3)])
summary(fit5)
plot(Mkt,fit5$fitted.values,ylab="fitted values")
abline(c(0,1))
fit6=lm(SMB~pcasv$x[,(1:3)])
summary(fit6)
plot(SMB,fit6$fitted.values,ylab="fitted values")
abline(c(0,1))
fit7=lm(HML~pcasv$x[,(1:3)])
summary(fit7)
plot(HML,fit7$fitted.values,ylab="fitted values")
abline(c(0,1))

```

## Bonus Questions: Note these questions are optional.
3. Exploratory data analysis II: 15 points

```{r}
## Problem 3
da <- read.table("d-exuseu-0516.txt",header=T)
head(da)
# (a)
rtn=diff(log(da$euro)) ## Compute log return
# (b)
basicStats(rtn)
# (c)
densityEX=density(rtn)
plot(densityEX,xlab="ln-rtn",ylab='euro',main='Density EX')
# (d)
t.test(rtn)
# (e)
normalTest(rtn)
qqnorm(rtn) # Quantile-quantile plot
qqline(rtn) # Include a line in the quantile-quantile plot.
# If empirical values are normally distributed
# then the quantiles should all be on the line.
```

## 4. Time-series model: 20 points

```{r}
### Problem 4
da=read.table("m-COILWTICO.txt",header=T)
head(da)
# (a)
oil=da$VALUE
doil=diff(oil)
dim(da)
# (b)
tdx <- c(1:362)/12+1986
plot(tdx,oil,xlab='year',ylab='coil',type='l')
plot(tdx[-1],doil,xlab='year',ylab='diff(oil)',type='l')
# (c)
# If you have not installed the package fUnitRoots please use the following command:
#install.packages("fUnitRoots")
require(fUnitRoots)
adfTest(oil,lags=11,type="c")
adfTest(doil,lags=11,type="c")
# (d)
acf(oil)
pacf(oil)
acf(doil)
pacf(doil)
# (e)
Box.test(doil,lag=12,type="Ljung")
# (f)
library("forecast")
ARoil=arima(doil,c(6,0,0))
ARoil
tsdiag(ARoil)
# You can also use the auto.arima command to fit an AR model
# ARoil2=auto.arima(doil,max.p = 20, max.q = 0, d = 0)
# ARoil2
# tsdiag(ARoil2)
# (g)
#You can use the auto.arima command to fit an ARMA model
# ARIMAoil=auto.arima(doil)
# ARIMAoil
# tsdiag(ARIMAoil)
ARIMAoil2=arima(doil,order=c(1,0,6))
ARIMAoil2
tsdiag(ARIMAoil2,gof=24)
# (h)
Oilpredict=predict(ARIMAoil2,4)
Oilpredict
lcl=Oilpredict$pred-1.96*Oilpredict$se
ucl=Oilpredict$pred+1.96*Oilpredict$se
cf=cbind(lcl,ucl)
cf
Oilforecast=forecast(ARIMAoil2,4)
Oilforecast
plot(Oilforecast)
# The next plot includes only the last 24 observations and labels
plot(Oilforecast,include=24,xlab="time",ylab="oil return",main="Prediction")
```

## 5. GARCH: 20 points

```{r}
#Problem 5
require(forecast)
da=read.table("d-amzn3dx0914.txt",header=T)
head(da)
rt=log(da$amzn+1)*100
# (a)
t.test(rt)
# (b)
acf(rt)
Box.test(rt,lag=10,type='Ljung')
# (c)
library(rugarch)
garch.norm = ugarchspec(mean.model=list(armaOrder=c(0,0)),
variance.model=list(garchOrder=c(1,1)))
amazonGarch = ugarchfit(data=rt, spec=garch.norm)
show(amazonGarch)
plot(amazonGarch, which="all")
plot(amazonGarch, which=9)
plot(amazonGarch, which=10)
plot(amazonGarch, which=11)
# (d)
arma.garch.t = ugarchspec(mean.model=list(armaOrder=c(0,0)),
variance.model=list(garchOrder=c(1,1)),
distribution.model = "std")
amazonGarch.t = ugarchfit(data=rt, spec=arma.garch.t)
show(amazonGarch.t)
plot(amazonGarch.t, which="all")
plot(amazonGarch.t, which=9)
plot(amazonGarch.t, which=10)
plot(amazonGarch.t, which=11)
# (f)
amazonforecast=ugarchforecast(amazonGarch.t, data = rt, n.ahead = 5)
show(amazonforecast)
plot(amazonforecast,which=1)
plot(amazonforecast,which=3)

```

## 6.Time-series model II: 30 bonus points

```{r}
#### Problem 6
require(forecast)
da <- read.table("m-globaltemp.txt",header=T)
dd <- da[,2:13]
xt <- c(t(dd))
zt <- diff(xt)
length(xt)
tdx <- c(1:1632)/12+1880
# (a)
par(mfcol=c(2,1))
plot(tdx,xt,xlab='year',ylab='temp',type='l')
plot(tdx[-1],zt,xlab='year',ylab='diff(temp)',type='l')
par(mfcol=c(1,1))
# (b)
require(fUnitRoots)
adfTest(xt,lags=11,type="c")
adfTest(zt,lags=11,type="c")
# (c)
t.test(zt)
# (d)
par(mfcol=c(2,1))
acf(zt)
pacf(zt)
par(mfcol=c(1,1))
# (e)
Box.test(zt,lag=12,type='Ljung')
# (f)
ARtemp=auto.arima(zt,max.p = 20, max.q = 0, d = 0)
ARtemp
tsdiag(ARtemp)
ARtemp2=arima(zt,order=c(11,0,0),include.mean=F)
ARtemp2
tsdiag(ARtemp2,gof=24)
# (g)
ARtemp3=arima(xt,order=c(11,1,0))
ARtemp3
PredictTemp <- predict(ARtemp3,12)
PredictTemp
# (h)
lcl <- PredictTemp$pred-1.96*PredictTemp$se
ucl <- PredictTemp$pred+1.96*PredictTemp$se
cf <- cbind(lcl,ucl)
cf[1:2,]
cf[1:12,]
# (i)
require(forecast)
ARIMAtemp=auto.arima(xt)
ARIMAtemp
tsdiag(ARIMAtemp,gof=24)
ARIMAtemp2=arima(zt,order=c(1,0,2),seasonal=list(order=c(1,0,0),period=12))
ARIMAtemp2
tsdiag(ARIMAtemp2,gof=24)
# (j)
ARIMAtemp3=arima(xt,order=c(1,1,2),seasonal=list(order=c(1,0,0),period=12))
ARIMAtemp3
tsdiag(ARIMAtemp3,gof=24)
PredictTemp=predict(ARIMAtemp3,12)
PredictTemp
lcl <- PredictTemp$pred-1.96*PredictTemp$se
ucl <- PredictTemp$pred+1.96*PredictTemp$se
cf <- cbind(lcl,ucl)
cf[1:2,]
cf[1:12,]
Tempforecast=forecast(ARIMAtemp3,12)
Tempforecast
plot(Tempforecast)
plot(Tempforecast,include=24,xlab="time",ylab="temperature",main="Prediction")

```

## 7.  GARCH II: 30 bonus points

```{r}
#Problem 7
da=read.table("d-sbux3dx-0715.txt",header=T)
head(da)
rtn=da[,3:6]
attach(rtn)
vw=log(da$vwretd+1)
# (a)
t.test(vw)
Box.test(vw,lag=12,type='Ljung')
acf(vw)
acf(vw^2)
garch.norm = ugarchspec(mean.model=list(armaOrder=c(0,0),include.mean = FALSE),
variance.model=list(garchOrder=c(1,1)))
vwGarch = ugarchfit(data=vw, spec=garch.norm)
show(vwGarch)
plot(vwGarch, which="all")
plot(vwGarch, which=9)
arma.garch.t = ugarchspec(mean.model=list(armaOrder=c(0,0),include.mean = FALSE),
variance.model=list(garchOrder=c(1,1)),
distribution.model = "std")
vwGarch.t = ugarchfit(data=vw, spec=arma.garch.t)
show(vwGarch.t)
plot(vwGarch.t, which="all")
plot(vwGarch.t, which=9)
# (b)
vwforecast=ugarchforecast(vwGarch.t, data = vw, n.ahead = 5)
show(vwforecast)
plot(vwforecast,which=1)
plot(vwforecast,which=3)
# (c)
arma.aparch.t = ugarchspec(mean.model=list(armaOrder=c(0,0),include.mean = FALSE),
variance.model=list(model="apARCH",
garchOrder=c(1,1)),
distribution.model = "std")
vwGarch.a = ugarchfit(data=vw, spec=arma.aparch.t)
show(vwGarch.a)

```

